"""add author normalized name

Revision ID: f3df81e2f33d
Revises: 3c37c79452bc
Create Date: 2026-03-12 23:49:38.994506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3df81e2f33d'
down_revision: Union[str, Sequence[str], None] = '3c37c79452bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('name_normalised', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_authors_name_normalised'), 'authors', ['name_normalised'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_authors_name_normalised'), table_name='authors')
    op.drop_column('authors', 'name_normalised')
    # ### end Alembic commands ###
